-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 00:26:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Programacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Programacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Programacion` DEFAULT CHARACTER SET utf8 ;
USE `Programacion` ;

-- -----------------------------------------------------
-- Table `Programacion`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Programacion`.`Usuarios` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(15) NULL,
  `Clave` VARCHAR(45) NULL,
  `EstaActivo` TINYINT NULL,
  PRIMARY KEY (`Codigo`, `Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Programacion`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Programacion`.`Producto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` DECIMAL(18,2) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Programacion`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Programacion`.`Pedidos` (
  `idPedidos` INT NOT NULL,
  `Decripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedidos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
